/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.github.javatlacati.pagare;

import com.github.javatlacati.pagare.entities.Pagare;

/**
 *
 * @author Ruslan López Carro <scherzo16 at gmail.com>
 */
public class RegistroDePagare extends javax.swing.JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TabAval1;
    private javax.swing.JButton btnAgregarAval;
    private javax.swing.JButton btnBorrarAval;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> cmbMoneda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblDatabaseId;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccionAval1;
    private javax.swing.JLabel lblFechaCreacion;
    private javax.swing.JLabel lblFechaVencimiento;
    private javax.swing.JLabel lblInteres;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNombreAval1;
    private javax.swing.JLabel lblNombreDeudor;
    private javax.swing.JLabel lblPoblacion;
    private javax.swing.JLabel lblPoblacionAval;
    private javax.swing.JLabel lblPoblacionDeudor;
    private javax.swing.JLabel lblPorciento;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefonoDeudor;
    private javax.swing.JPanel pnlAval;
    private javax.swing.JPanel pnlDeudor;
    private javax.swing.JPanel pnlLocacion;
    private javax.swing.JScrollPane scrlDireccionAval1;
    private javax.swing.JScrollPane scrlDireccionDeudor;
    private javax.swing.JSpinner spinInteres;
    private javax.swing.JSpinner spinerSerie;
    private javax.swing.JTabbedPane tabAvales;
    private javax.swing.JTextArea txtAreaireccionDeudor;
    private javax.swing.JTextField txtDatabaseId;
    private javax.swing.JTextArea txtDireccionAval1;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtFechaVencimiento;
    private javax.swing.JTextField txtNombreAval1;
    private javax.swing.JTextField txtNombreDeudor;
    private javax.swing.JTextField txtPoblacion;
    private javax.swing.JTextField txtPoblacionAval;
    private javax.swing.JTextField txtPoblacionDeudor;
    private javax.swing.JTextField txtTelefonoAval1;
    private javax.swing.JTextField txtTelefonoDeudor;
    // End of variables declaration//GEN-END:variables

    private Pagare pagare =new Pagare();
    
    /** Creates new form RegistroDePagare */
    public RegistroDePagare() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDatabaseId = new javax.swing.JLabel();
        txtDatabaseId = new javax.swing.JTextField();
        lblMonto = new javax.swing.JLabel();
        cmbMoneda = new javax.swing.JComboBox<>();
        pnlLocacion = new javax.swing.JPanel();
        lblPoblacion = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        lblFechaCreacion = new javax.swing.JLabel();
        txtFechaCreacion = new javax.swing.JTextField();
        lblFechaVencimiento = new javax.swing.JLabel();
        txtFechaVencimiento = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblSerie = new javax.swing.JLabel();
        spinerSerie = new javax.swing.JSpinner();
        pnlDeudor = new javax.swing.JPanel();
        lblNombreDeudor = new javax.swing.JLabel();
        txtNombreDeudor = new javax.swing.JTextField();
        lblPoblacionDeudor = new javax.swing.JLabel();
        txtTelefonoDeudor = new javax.swing.JTextField();
        lblTelefonoDeudor = new javax.swing.JLabel();
        txtPoblacionDeudor = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        scrlDireccionDeudor = new javax.swing.JScrollPane();
        txtAreaireccionDeudor = new javax.swing.JTextArea();
        lblInteres = new javax.swing.JLabel();
        spinInteres = new javax.swing.JSpinner();
        lblPorciento = new javax.swing.JLabel();
        pnlAval = new javax.swing.JPanel();
        tabAvales = new javax.swing.JTabbedPane();
        TabAval1 = new javax.swing.JPanel();
        lblNombreAval1 = new javax.swing.JLabel();
        txtNombreAval1 = new javax.swing.JTextField();
        lblPoblacionAval = new javax.swing.JLabel();
        txtPoblacionAval = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefonoAval1 = new javax.swing.JTextField();
        lblDireccionAval1 = new javax.swing.JLabel();
        scrlDireccionAval1 = new javax.swing.JScrollPane();
        txtDireccionAval1 = new javax.swing.JTextArea();
        btnAgregarAval = new javax.swing.JButton();
        btnBorrarAval = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDatabaseId.setText("No.");

        lblMonto.setText("Bueno por: $");

        cmbMoneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MXN", "EUR", "USD" }));

        pnlLocacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubicación"));

        lblPoblacion.setText("Población");

        lblFechaCreacion.setText("Fecha de creación");

        lblFechaVencimiento.setText("Fecha de vencimiento:");

        javax.swing.GroupLayout pnlLocacionLayout = new javax.swing.GroupLayout(pnlLocacion);
        pnlLocacion.setLayout(pnlLocacionLayout);
        pnlLocacionLayout.setHorizontalGroup(
            pnlLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPoblacion)
                    .addComponent(txtFechaCreacion)
                    .addComponent(txtFechaVencimiento)
                    .addGroup(pnlLocacionLayout.createSequentialGroup()
                        .addGroup(pnlLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPoblacion)
                            .addComponent(lblFechaCreacion)
                            .addComponent(lblFechaVencimiento))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLocacionLayout.setVerticalGroup(
            pnlLocacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLocacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPoblacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaCreacion)
                .addGap(18, 18, 18)
                .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaVencimiento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");

        btnCancelar.setText("Cancelar");

        lblSerie.setText("Serie de");

        spinerSerie.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        pnlDeudor.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Deudor"));

        lblNombreDeudor.setText("Nombre completo:");

        lblPoblacionDeudor.setText("Población");

        lblTelefonoDeudor.setText("Teléfono:");

        lblDireccion.setText("Dirección");

        txtAreaireccionDeudor.setColumns(20);
        txtAreaireccionDeudor.setRows(5);
        scrlDireccionDeudor.setViewportView(txtAreaireccionDeudor);

        javax.swing.GroupLayout pnlDeudorLayout = new javax.swing.GroupLayout(pnlDeudor);
        pnlDeudor.setLayout(pnlDeudorLayout);
        pnlDeudorLayout.setHorizontalGroup(
            pnlDeudorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeudorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDeudorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreDeudor)
                    .addComponent(lblTelefonoDeudor)
                    .addComponent(lblPoblacionDeudor)
                    .addComponent(lblDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeudorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPoblacionDeudor)
                    .addComponent(txtNombreDeudor)
                    .addComponent(txtTelefonoDeudor)
                    .addComponent(scrlDireccionDeudor, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDeudorLayout.setVerticalGroup(
            pnlDeudorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeudorLayout.createSequentialGroup()
                .addGroup(pnlDeudorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreDeudor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreDeudor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeudorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoDeudor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoDeudor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDeudorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPoblacionDeudor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoblacionDeudor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDeudorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccion)
                    .addComponent(scrlDireccionDeudor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblInteres.setText("Interés mensual:");

        spinInteres.setModel(new javax.swing.SpinnerNumberModel(20, 0, 100, 1));

        lblPorciento.setText("%");

        pnlAval.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del aval"));

        lblNombreAval1.setText("Nombre Completo");

        lblPoblacionAval.setText("Población:");

        lblTelefono.setText("Teléfono");

        lblDireccionAval1.setText("Dirección:");

        txtDireccionAval1.setColumns(20);
        txtDireccionAval1.setRows(5);
        scrlDireccionAval1.setViewportView(txtDireccionAval1);

        btnAgregarAval.setText("Agregar otro Aval");

        btnBorrarAval.setText("Borrar Aval");

        javax.swing.GroupLayout TabAval1Layout = new javax.swing.GroupLayout(TabAval1);
        TabAval1.setLayout(TabAval1Layout);
        TabAval1Layout.setHorizontalGroup(
            TabAval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabAval1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabAval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabAval1Layout.createSequentialGroup()
                        .addGroup(TabAval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAval1)
                            .addComponent(lblPoblacionAval)
                            .addComponent(lblDireccionAval1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TabAval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreAval1)
                            .addGroup(TabAval1Layout.createSequentialGroup()
                                .addComponent(txtPoblacionAval, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTelefono)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefonoAval1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(scrlDireccionAval1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabAval1Layout.createSequentialGroup()
                        .addComponent(btnBorrarAval)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarAval)))
                .addContainerGap())
        );
        TabAval1Layout.setVerticalGroup(
            TabAval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabAval1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TabAval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAval1)
                    .addComponent(txtNombreAval1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TabAval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPoblacionAval)
                    .addComponent(txtPoblacionAval, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefonoAval1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TabAval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDireccionAval1)
                    .addComponent(scrlDireccionAval1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(TabAval1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabAval1Layout.createSequentialGroup()
                        .addComponent(btnAgregarAval)
                        .addContainerGap())
                    .addComponent(btnBorrarAval, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        tabAvales.addTab("Aval 1", TabAval1);

        javax.swing.GroupLayout pnlAvalLayout = new javax.swing.GroupLayout(pnlAval);
        pnlAval.setLayout(pnlAvalLayout);
        pnlAvalLayout.setHorizontalGroup(
            pnlAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvalLayout.createSequentialGroup()
                .addComponent(tabAvales)
                .addContainerGap())
        );
        pnlAvalLayout.setVerticalGroup(
            pnlAvalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabAvales, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 99, 1));

        jLabel1.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblDatabaseId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatabaseId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimir)
                        .addGap(160, 160, 160)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMonto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spinerSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInteres)
                        .addGap(18, 18, 18)
                        .addComponent(spinInteres)
                        .addGap(10, 10, 10)
                        .addComponent(lblPorciento))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlLocacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDeudor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatabaseId)
                    .addComponent(txtDatabaseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMonto)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSerie)
                        .addComponent(spinerSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInteres)
                        .addComponent(spinInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPorciento)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlLocacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDeudor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnImprimir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        final int maxSerie = (Integer) spinerSerie.getValue();
        for (int i = 1; i <= maxSerie; i++) {
            System.out.println("Pagaré No. "+i+" Bueno por $");
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDePagare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDePagare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDePagare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDePagare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDePagare().setVisible(true);
            }
        });
    }

}
